version: 2.1
orbs:
	aws-s3: circle/ci:aws-s3@1.0.0
jobs:
	setup:
		docker:
			- image: circleci/node:11.10.1
		steps:
			- checkout
			- run:
					name: "Node version"
					command: echo node -v
			- run:
					name: "NPM version"
					command: echo npm -v
			- run:
					name: "Install dependencies"
					command: npm install
	test:
		docker:
			- image: circleci/node:11.10.1
		steps:
			- checkout
			- run: npm test
	deploy2s3:
		docker:
			- image: circleci/python:2.7
		branches:
			only:
				- master
		steps:
			- checkout
			- run:
				name: "Build bundle"
				command: parcel build index.html --out-dir dist/ --no-source-maps --detailed-report
			# Sync assests
			- aws-s3/sync:
				from: dist
				to: s3://brewkrew.io
				arguments: |
					--exclude *.html \
					--cache-control 'max-age=31536000, public'
				overwrite: true
			# Sync html
			- aws-s3/sync:
				from: dist
				to: s3://brewkrew.io
				arguments: |
					--exclude *.js \
					--exclude *.css \
					--exclude *.jpg \
					--cache-control 'no-cache'
				overwrite: true
workflows:
	build-test-deploy:
		jobs:
			- setup
			- test
			- deploy2s3


 
 
