version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.9
executors:
  node-python:
    docker:
      - image: circleci/node:11.10.1
        name: node
      - image: circleci/python:2.7
        name: python
jobs:
  setup:
    executor: node-python
    steps:
      - checkout
      - run:
          name: "Node version"
          command: node -v
      - run:
          name: "NPM version"
          command: npm -v
      - restore_cache: # special step to restore the dependency cache
          key: npm-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Install dependencies"
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: npm-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    executor: node-python
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: npm-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Eslint"
          command: npm run test
  deploy2s3:
    executor: node-python
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: npm-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Build bundle"
          command: npm run build
      # Sync assests
      - aws-s3/sync:
          from: dist
          to: s3://brewkrew.io
          arguments: |
            --exclude *.html \
            --cache-control 'max-age=31536000, public'
          overwrite: true
      # Sync html
      - aws-s3/sync:
          from: dist
          to: s3://brewkrew.io
          arguments: |
            --exclude *.js \
            --exclude *.css \
            --exclude *.jpg \
            --cache-control 'no-cache'
          overwrite: true
workflows:
  build-test-deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - deploy2s3:
          filters:
            branches:
              only: master
          requires:
            - test
